name: agrismart
description: "A new Agricultural application."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.9.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  english_words: ^4.0.0
  provider: ^6.1.2
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  sliding_up_panel: ^2.0.0+1
  email_validator: ^2.0.1
  string_validator: ^0.3.0
  path_provider: ^2.0.4
  shared_preferences: ^2.0.8
  flutter_iconly: ^1.0.2
  url_launcher: ^6.0.0
  http: ^1.0.0
  flutter_dotenv: ^5.2.1
  easy_stepper: ^0.7.3
  uuid: ^4.5.1
  flutter_stripe: ^11.5.0






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  google_nav_bar: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - asset/
    - assets/user.jpg
    - assets/logo.jpg

  fonts:
    - family: NimbusSanL
      fonts:
        - asset: fonts/NimbusSanL-Bol.otf
          weight: 700
        - asset: fonts/NimbusSanL-RegIta.otf
          style: italic
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/AgriSm.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true
